# Generated by Django 5.2.9 on 2026-01-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Plant Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('uses', models.TextField(verbose_name='Uses')),
                ('how_to_grow', models.TextField(verbose_name='How to Grow')),
                ('how_to_use', models.TextField(verbose_name='How to Use')),
                ('image', models.ImageField(blank=True, null=True, upload_to='garden/plants/', verbose_name='Plant Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'ordering': ['name'],
            },
        ),
    ]
