# Generated by Django 5.2.9 on 2026-01-29 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planted', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Growing', 'Growing'), ('Harvested', 'Harvested')], default='Planning', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='garden.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_planted'],
                'unique_together': {('user', 'plant')},
            },
        ),
    ]
