# Generated by Django 5.2.9 on 2026-01-29 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_userplant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='garden/journal/', verbose_name='Photo')),
                ('user_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='garden.userplant')),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
    ]
