# Generated by Django 5.2.9 on 2026-02-19 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_plantjournal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='is_for_swap',
            field=models.BooleanField(default=False, verbose_name='Available for Swap/Share'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='garden/qrcodes/'),
        ),
        migrations.CreateModel(
            name='GardenExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Seeds', 'Seeds/Plants'), ('Soil', 'Soil/Amendments'), ('Tools', 'Tools'), ('Equipment', 'Equipment'), ('Other', 'Other')], default='Other', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_expenses', to=settings.AUTH_USER_MODEL)),
                ('user_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='garden.userplant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GardenTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('Watering', 'Watering'), ('Fertilizing', 'Fertilizing'), ('Pruning', 'Pruning'), ('Pest Control', 'Pest Control'), ('Other', 'Other')], max_length=50)),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('recurrence_days', models.IntegerField(blank=True, help_text='Repeat every X days', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='garden.userplant')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField(help_text='Quantity harvested')),
                ('unit', models.CharField(default='kg', help_text='Unit (e.g., kg, count, lbs)', max_length=50)),
                ('rating', models.IntegerField(default=5, help_text='Quality rating (1-5)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('user_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='garden.userplant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('Pest', 'Pest'), ('Disease', 'Disease'), ('Nutrient', 'Nutrient Deficiency'), ('Other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20)),
                ('status', models.CharField(choices=[('Identified', 'Identified'), ('Treating', 'Treating'), ('Resolved', 'Resolved')], default='Identified', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='garden/health/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_logged', models.DateField(auto_now_add=True)),
                ('user_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='garden.userplant')),
            ],
            options={
                'ordering': ['-date_logged'],
            },
        ),
    ]
