# Generated by Django 5.2.9 on 2026-04-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Upload screenshot of UPI transaction', null=True, upload_to='payment_proofs/'),
        ),
    ]
