# Generated by Django 5.2.9 on 2026-04-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upi_id',
            field=models.CharField(blank=True, help_text='e.g. yourname@upi (required for getting payments)', max_length=50),
        ),
    ]
