# Generated by Django 5.2.9 on 2026-03-31 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('health', 'Plant Health Checkup'), ('disease', 'Plant Disease Detection'), ('yield', 'Crop Yield Prediction')], max_length=20, verbose_name='Check Type')),
                ('image', models.ImageField(upload_to='checks/uploads/%Y/%m/', verbose_name='Plant Image')),
                ('result_title', models.CharField(blank=True, default='', max_length=300, verbose_name='Result Title')),
                ('result_summary', models.TextField(blank=True, default='', verbose_name='Result Summary')),
                ('result_details', models.JSONField(blank=True, null=True, verbose_name='Detailed Results')),
                ('severity', models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=20, verbose_name='Severity')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='Confidence %')),
                ('recommendations', models.TextField(blank=True, default='', verbose_name='Recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plant Check',
                'verbose_name_plural': 'Plant Checks',
                'ordering': ['-created_at'],
            },
        ),
    ]
