# Generated by Django 5.2.9 on 2026-03-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcheck',
            name='check_type',
            field=models.CharField(choices=[('health', 'Plant Health Checkup'), ('disease', 'Plant Disease Detection'), ('yield', 'Crop Yield Prediction'), ('encyclopedia', 'Plants Encyclopedia')], max_length=20, verbose_name='Check Type'),
        ),
    ]
