# Generated by Django 5.2.9 on 2026-04-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_alter_plantcheck_check_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantcheck',
            name='proposed_crop',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proposed Crop'),
        ),
        migrations.AddField(
            model_name='plantcheck',
            name='rainfall',
            field=models.FloatField(blank=True, null=True, verbose_name='Rainfall (mm/year)'),
        ),
        migrations.AddField(
            model_name='plantcheck',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soil Type'),
        ),
        migrations.AddField(
            model_name='plantcheck',
            name='temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='plantcheck',
            name='check_type',
            field=models.CharField(choices=[('health', 'Plant Health Checkup'), ('disease', 'Plant Disease Detection'), ('yield', 'Crop Recommendation'), ('encyclopedia', 'Plants Encyclopedia')], max_length=20, verbose_name='Check Type'),
        ),
        migrations.AlterField(
            model_name='plantcheck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='checks/uploads/%Y/%m/', verbose_name='Plant Image'),
        ),
    ]
